# Generated by Django 4.2.17 on 2025-01-08 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('giftbox_1', 'Giftbox 1'), ('giftbox_2', 'Giftbox 2'), ('giftbox_3', 'Giftbox 3'), ('giftbox_4', 'Giftbox 4'), ('giftbox_5', 'Giftbox 5'), ('giftbox_6', 'Giftbox 6')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('giftbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.giftbox')),
            ],
        ),
    ]
